version: "3.1"
services:

  api:
    container_name: api-service
    build: ../dist
    depends_on:
      - mongodb
    ports:
      - 7001:7001
    links:
      - mongodb
    environment:
      - PORT=7001

  mongodb:
    container_name: api-mongodb
    restart: always
    image: mvertes/alpine-mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  nginx:
      container_name: nginx
      depends_on:
        - mongodb
        - api
      build: ./nginx
      links:
        - api
      ports:
        - "80:80"
        - "443:443"
      